name: Awesome

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: yarn install
      - run: yarn awesome
        env:
          ISSUES_GITHUB_TOKEN: ${{ secrets.ISSUES_GITHUB_TOKEN }}
