name: Discord issues

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    name: Discord issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: yarn install
      - run: yarn discord:issues
        env:
          DISCORD_ID: ${{ secrets.DISCORD_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          ISSUES_GITHUB_TOKEN: ${{ secrets.ISSUES_GITHUB_TOKEN }}

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: '[skip ci] good-first issue update'
