name: Fetch Gas prices

on:
  workflow_dispatch:

jobs:
  build:
    name: Fetch latest gas prices
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: yarn install
      - name: Fetch Gas prices
        run: yarn gas:fetch
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          INFURA_KEY: ${{ secrets.INFURA_KEY }}